version: "3.7"

services:
#  ulimits:
#    nofile:
#      soft: 65536
#      hard: 65536
  sonarqube:
    image: sonarqube
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
#    networks:
#      - randdnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
  db:
    image: postgres
#    networks:
#      - randdnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  jenkins:
    build:
      context: .
      args:
        USER_GID: $USER_GID
        USER_ID: $USER_ID
    image: randdbpmnpipeline/jenkins
    environment:
      CASC_JENKINS_CONFIG: $CASC_JENKINS_CONFIG
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      ANSIBLE_CONFIG: /home/jenkins/ansible/ansible.cfg
    ports:
      - 9080:8080
#    networks:
#      - randdnet
    volumes:
      - $HOME/data/jenkins:$JENKINS_HOME
      - ./bashrc:$JENKINS_HOME/.bashrc
      - ./jenkins.yml:$CASC_JENKINS_CONFIG
      - /var/run/docker.sock:/var/run/docker.sock
#  networks:
#    randdnet:
#      external:
#        name: randdnet
